# Generated by Django 5.0.4 on 2026-02-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_varianttype_remove_product_variants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
